package br.com.anteros.commons.services.rest.repository;

import br.com.anteros.security.store.sql.domain.Client;
import br.com.anteros.persistence.session.repository.SQLRepository;

/**
*  Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
**/

public interface ClientRepository extends SQLRepository<Client, Long> {

}
