package br.com.anteros.commons.services.rest.repository;

import java.util.List;

import br.com.anteros.persistence.session.repository.SQLRepository;
import br.com.anteros.security.store.sql.domain.SecuritySession;

/**
*  Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
**/

public interface SecuritySessionRepository extends SQLRepository<SecuritySession, Long> {

	List<SecuritySession> getSessionsBySystem(String system);

}
