package br.com.anteros.commons.services.rest.repository;

import java.util.List;

import br.com.anteros.persistence.session.repository.SQLRepository;
import br.com.anteros.security.store.sql.domain.Resource;
import br.com.anteros.security.store.sql.domain.User;

/**
*  Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
**/

public interface UserRepository extends SQLRepository<User, Long> {

	User getUserByLoginName(String login);

	

}
