package br.com.anteros.commons.services.rest.resource.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import br.com.anteros.security.store.sql.domain.AccessToken;
import br.com.anteros.commons.services.rest.service.AccessTokenService;
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at 29/12/2019 08:16:42
**/

@RestController
@RequestMapping(value = "/v1/accessToken")
public class AccessTokenResource extends AbstractSQLResourceRest<AccessToken, Long> {

	@Autowired
	@Lazy
	private AccessTokenService accessTokenService;

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<AccessToken, Long> getService() {
		return accessTokenService;
	}
	
	@Override
	protected Page<AccessToken> createConcretePage(List<AccessToken> content, PageRequest pageRequest,
			long totalElements) {
		return new PageAccessToken(content, pageRequest, totalElements);
	}

	class PageAccessToken extends PageImpl<AccessToken> {
		public PageAccessToken(List<AccessToken> content) {
			super(content);
		}

		public PageAccessToken(List<AccessToken> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<AccessToken> createConcreteList(List<AccessToken> result) {
		return new ListAccessToken(result);
	}
	
	class ListAccessToken extends ArrayList<AccessToken>{
		public ListAccessToken(Collection<? extends AccessToken> c) {
			super(c);
		}
	}
}