package br.com.anteros.commons.services.rest.resource.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import br.com.anteros.security.store.sql.domain.Approval;
import br.com.anteros.commons.services.rest.service.ApprovalService;
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at 29/12/2019 08:16:42
**/

@RestController
@RequestMapping(value = "/v1/approval")
public class ApprovalResource extends AbstractSQLResourceRest<Approval, Long> {

	@Autowired
	@Lazy
	private ApprovalService approvalService;

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<Approval, Long> getService() {
		return approvalService;
	}
	
	@Override
	protected Page<Approval> createConcretePage(List<Approval> content, PageRequest pageRequest,
			long totalElements) {
		return new PageApproval(content, pageRequest, totalElements);
	}

	class PageApproval extends PageImpl<Approval> {
		public PageApproval(List<Approval> content) {
			super(content);
		}

		public PageApproval(List<Approval> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<Approval> createConcreteList(List<Approval> result) {
		return new ListApproval(result);
	}
	
	class ListApproval extends ArrayList<Approval>{
		public ListApproval(Collection<? extends Approval> c) {
			super(c);
		}
	}
}