package br.com.anteros.commons.services.rest.resource.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import br.com.anteros.security.store.sql.domain.Client;
import br.com.anteros.commons.services.rest.service.ClientService;
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at 29/12/2019 08:16:42
**/

@RestController
@RequestMapping(value = "/v1/client")
public class ClientResource extends AbstractSQLResourceRest<Client, Long> {

	@Autowired
	@Lazy
	private ClientService clientService;

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<Client, Long> getService() {
		return clientService;
	}
	
	@Override
	protected Page<Client> createConcretePage(List<Client> content, PageRequest pageRequest,
			long totalElements) {
		return new PageClient(content, pageRequest, totalElements);
	}

	class PageClient extends PageImpl<Client> {
		public PageClient(List<Client> content) {
			super(content);
		}

		public PageClient(List<Client> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<Client> createConcreteList(List<Client> result) {
		return new ListClient(result);
	}
	
	class ListClient extends ArrayList<Client>{
		public ListClient(Collection<? extends Client> c) {
			super(c);
		}
	}
}