package br.com.anteros.commons.services.rest.resource.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import br.com.anteros.security.store.sql.domain.Group;
import br.com.anteros.commons.services.rest.service.GroupService;
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at 29/12/2019 08:16:42
**/

@RestController
@RequestMapping(value = "/v1/group")
public class GroupResource extends AbstractSQLResourceRest<Group, Long> {

	@Autowired
	@Lazy
	private GroupService groupService;

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<Group, Long> getService() {
		return groupService;
	}
	
	@Override
	protected Page<Group> createConcretePage(List<Group> content, PageRequest pageRequest,
			long totalElements) {
		return new PageGroup(content, pageRequest, totalElements);
	}

	class PageGroup extends PageImpl<Group> {
		public PageGroup(List<Group> content) {
			super(content);
		}

		public PageGroup(List<Group> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<Group> createConcreteList(List<Group> result) {
		return new ListGroup(result);
	}
	
	class ListGroup extends ArrayList<Group>{
		public ListGroup(Collection<? extends Group> c) {
			super(c);
		}
	}
}