package br.com.anteros.commons.services.rest.resource.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import br.com.anteros.security.store.sql.domain.Profile;
import br.com.anteros.commons.services.rest.service.ProfileService;
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at 29/12/2019 08:16:42
**/

@RestController
@RequestMapping(value = "/v1/profile")
public class ProfileResource extends AbstractSQLResourceRest<Profile, Long> {

	@Autowired
	@Lazy
	private ProfileService profileService;

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<Profile, Long> getService() {
		return profileService;
	}
	
	@Override
	protected Page<Profile> createConcretePage(List<Profile> content, PageRequest pageRequest,
			long totalElements) {
		return new PageProfile(content, pageRequest, totalElements);
	}

	class PageProfile extends PageImpl<Profile> {
		public PageProfile(List<Profile> content) {
			super(content);
		}

		public PageProfile(List<Profile> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<Profile> createConcreteList(List<Profile> result) {
		return new ListProfile(result);
	}
	
	class ListProfile extends ArrayList<Profile>{
		public ListProfile(Collection<? extends Profile> c) {
			super(c);
		}
	}
}