package br.com.anteros.commons.services.rest.resource.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import br.com.anteros.security.store.sql.domain.RefreshToken;
import br.com.anteros.commons.services.rest.service.RefreshTokenService;
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at 29/12/2019 08:16:42
**/

@RestController
@RequestMapping(value = "/v1/refreshToken")
public class RefreshTokenResource extends AbstractSQLResourceRest<RefreshToken, Long> {

	@Autowired
	@Lazy
	private RefreshTokenService refreshTokenService;

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<RefreshToken, Long> getService() {
		return refreshTokenService;
	}
	
	@Override
	protected Page<RefreshToken> createConcretePage(List<RefreshToken> content, PageRequest pageRequest,
			long totalElements) {
		return new PageRefreshToken(content, pageRequest, totalElements);
	}

	class PageRefreshToken extends PageImpl<RefreshToken> {
		public PageRefreshToken(List<RefreshToken> content) {
			super(content);
		}

		public PageRefreshToken(List<RefreshToken> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<RefreshToken> createConcreteList(List<RefreshToken> result) {
		return new ListRefreshToken(result);
	}
	
	class ListRefreshToken extends ArrayList<RefreshToken>{
		public ListRefreshToken(Collection<? extends RefreshToken> c) {
			super(c);
		}
	}
}