package br.com.anteros.commons.services.rest.resource.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import br.com.anteros.security.store.sql.domain.Security;
import br.com.anteros.commons.services.rest.service.SecurityService;
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at 29/12/2019 08:16:42
**/

@RestController
@RequestMapping(value = "/v1/security")
public class SecurityResource extends AbstractSQLResourceRest<Security, Long> {

	@Autowired
	@Lazy
	private SecurityService securityService;

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<Security, Long> getService() {
		return securityService;
	}
	
	@Override
	protected Page<Security> createConcretePage(List<Security> content, PageRequest pageRequest,
			long totalElements) {
		return new PageSecurity(content, pageRequest, totalElements);
	}

	class PageSecurity extends PageImpl<Security> {
		public PageSecurity(List<Security> content) {
			super(content);
		}

		public PageSecurity(List<Security> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<Security> createConcreteList(List<Security> result) {
		return new ListSecurity(result);
	}
	
	class ListSecurity extends ArrayList<Security>{
		public ListSecurity(Collection<? extends Security> c) {
			super(c);
		}
	}
}