package br.com.anteros.commons.services.rest.resource.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import br.com.anteros.security.store.sql.domain.System;
import br.com.anteros.commons.services.rest.service.SystemService;
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at 29/12/2019 08:16:42
**/

@RestController
@RequestMapping(value = "/v1/system")
public class SystemResource extends AbstractSQLResourceRest<System, Long> {

	@Autowired
	@Lazy
	private SystemService systemService;

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<System, Long> getService() {
		return systemService;
	}
	
	@Override
	protected Page<System> createConcretePage(List<System> content, PageRequest pageRequest,
			long totalElements) {
		return new PageSystem(content, pageRequest, totalElements);
	}

	class PageSystem extends PageImpl<System> {
		public PageSystem(List<System> content) {
			super(content);
		}

		public PageSystem(List<System> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<System> createConcreteList(List<System> result) {
		return new ListSystem(result);
	}
	
	class ListSystem extends ArrayList<System>{
		public ListSystem(Collection<? extends System> c) {
			super(c);
		}
	}
}