package br.com.anteros.commons.services.rest.resource.v1;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.context.annotation.Lazy;

import br.com.anteros.security.store.sql.domain.Terminal;
import br.com.anteros.commons.services.rest.service.TerminalService;
import br.com.anteros.persistence.session.service.SQLService;
import br.com.anteros.security.spring.AnterosSecurityManager;
import br.com.anteros.spring.web.resource.AbstractSQLResourceRest;
import br.com.anteros.persistence.session.repository.Page;
import br.com.anteros.persistence.session.repository.PageRequest;
import br.com.anteros.persistence.session.repository.Pageable;
import br.com.anteros.persistence.session.repository.impl.PageImpl;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
*  Generated by Anteros Generator Maven Plugin at 29/12/2019 08:16:42
**/

@RestController
@RequestMapping(value = "/v1/terminal")
public class TerminalResource extends AbstractSQLResourceRest<Terminal, Long> {

	@Autowired
	@Lazy
	private TerminalService terminalService;

	@Autowired
	@Lazy
	protected AnterosSecurityManager anterosSecurityManager;

	@Override
	public SQLService<Terminal, Long> getService() {
		return terminalService;
	}
	
	@Override
	protected Page<Terminal> createConcretePage(List<Terminal> content, PageRequest pageRequest,
			long totalElements) {
		return new PageTerminal(content, pageRequest, totalElements);
	}

	class PageTerminal extends PageImpl<Terminal> {
		public PageTerminal(List<Terminal> content) {
			super(content);
		}

		public PageTerminal(List<Terminal> content, Pageable pageable, long total) {
			super(content, pageable, total);
		}
	}
	
	@Override
	protected List<Terminal> createConcreteList(List<Terminal> result) {
		return new ListTerminal(result);
	}
	
	class ListTerminal extends ArrayList<Terminal>{
		public ListTerminal(Collection<? extends Terminal> c) {
			super(c);
		}
	}
}