package br.com.anteros.commons.services.rest.service.impl;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;

import br.com.anteros.security.store.sql.domain.AccessTimeInterval;
import br.com.anteros.commons.services.rest.service.AccessTimeIntervalService;
import br.com.anteros.spring.service.SpringSQLService;

/**
*  Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
**/

@Service("accessTimeIntervalService")
@Scope("prototype")
public class AccessTimeIntervalServiceImpl extends SpringSQLService<AccessTimeInterval, Long> implements AccessTimeIntervalService {

}
