package br.com.anteros.commons.services.rest.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;

import br.com.anteros.commons.services.rest.repository.SecurityAccessRepository;
import br.com.anteros.commons.services.rest.service.SecurityAccessService;
import br.com.anteros.security.store.sql.domain.SecurityAccess;
import br.com.anteros.spring.service.SpringSQLService;

/**
*  Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
**/

@Service("securityAccessService")
@Scope("prototype")
public class SecurityAccessServiceImpl extends SpringSQLService<SecurityAccess, Long> implements SecurityAccessService {
	
	@Autowired
	private SecurityAccessRepository securityAccessRepository;

	@Override
	public List<SecurityAccess> getSecurityAccessBySystem(String system) {
		return securityAccessRepository.getSecurityAccessBySystem(system);
	}

}
