package br.com.anteros.commons.services.rest.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;

import br.com.anteros.commons.services.rest.repository.UserRepository;
import br.com.anteros.commons.services.rest.service.UserService;
import br.com.anteros.security.store.sql.domain.User;
import br.com.anteros.spring.service.SpringSQLService;

/**
*  Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
**/

@Service("userService")
@Scope("prototype")
public class UserServiceImpl extends SpringSQLService<User, Long> implements UserService {

	@Autowired
	private UserRepository userRepository;

	@Override
	public User getUserByLoginName(String login) {		
		return userRepository.getUserByLoginName(login);
	}
	
}
