package br.com.anteros.commons.services.rest.service;

import br.com.anteros.security.spring.ResourceSecured;
import br.com.anteros.security.spring.sql.service.SQLServiceSecured;
import br.com.anteros.security.store.sql.domain.Security;

/**
*  Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
**/

@ResourceSecured(resourceName = "Security", description = "Security")
public interface SecurityService extends SQLServiceSecured<Security, Long> {

}
