package br.com.anteros.commons.services.rest.repository.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Qualifier;

import br.com.anteros.security.store.sql.domain.AccessTimeInterval;
import br.com.anteros.commons.services.rest.repository.AccessTimeIntervalRepository;
import br.com.anteros.persistence.session.SQLSessionFactory;
import br.com.anteros.persistence.session.repository.impl.GenericSQLRepository;

/**
*  Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
**/

@Repository("accessTimeIntervalRepository")
public class AccessTimeIntervalRepositoryImpl extends GenericSQLRepository<AccessTimeInterval, Long> implements AccessTimeIntervalRepository {

	@Autowired
	public AccessTimeIntervalRepositoryImpl(@Qualifier("sessionFactorySQL")SQLSessionFactory sessionFactory) {
		super(sessionFactory);
	}

}
