package br.com.anteros.commons.services.rest.repository.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Repository;

import br.com.anteros.commons.services.rest.repository.SecuritySessionRepository;
import br.com.anteros.persistence.session.SQLSessionFactory;
import br.com.anteros.persistence.session.repository.impl.GenericSQLRepository;
import br.com.anteros.security.store.sql.domain.Resource;
import br.com.anteros.security.store.sql.domain.SecuritySession;
import br.com.anteros.security.store.sql.domain.TSecuritySession;

/**
 * Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
 **/

@Repository("securitySessionRepository")
public class SecuritySessionRepositoryImpl extends GenericSQLRepository<SecuritySession, Long>
		implements SecuritySessionRepository {

	@Autowired
	public SecuritySessionRepositoryImpl(@Qualifier("sessionFactorySQL") SQLSessionFactory sessionFactory) {
		super(sessionFactory);
	}

	@Override
	public List<SecuritySession> getSessionsBySystem(String system) {
		TSecuritySession tSecuritySession = new TSecuritySession("SEC");
		return this.createObjectQuery().from(tSecuritySession).where(tSecuritySession.system.eq(system))
				.orderBy(tSecuritySession.dtSessionLogin.desc())
				.list(tSecuritySession);
	}

}
