package br.com.anteros.commons.services.rest.repository.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Repository;

import br.com.anteros.commons.services.rest.repository.SecurityAccessRepository;
import br.com.anteros.persistence.session.SQLSessionFactory;
import br.com.anteros.persistence.session.repository.impl.GenericSQLRepository;
import br.com.anteros.security.store.sql.domain.SecurityAccess;
import br.com.anteros.security.store.sql.domain.TSecurityAccess;

/**
 * Generated by Anteros Generator Maven Plugin at 23/10/2019 10:25:34
 **/

@Repository("securityAccessRepository")
public class SecurityAccessRepositoryImpl extends GenericSQLRepository<SecurityAccess, Long>
		implements SecurityAccessRepository {

	@Autowired
	public SecurityAccessRepositoryImpl(@Qualifier("sessionFactorySQL") SQLSessionFactory sessionFactory) {
		super(sessionFactory);
	}

	@Override
	public List<SecurityAccess> getSecurityAccessBySystem(String system) {
		TSecurityAccess tSecurityAccess = new TSecurityAccess("SEC");
		return this.createObjectQuery().from(tSecurityAccess).where(tSecurityAccess.system.name.eq(system))
				.orderBy(tSecurityAccess.terminal.name.asc(),tSecurityAccess.security.description.asc())
				.list(tSecurityAccess);
	}

}
